# Change these first
owner: lonsofore # Your GitHub organization or username, where this repository lives
repo: cod2-ru-uptime # The name of this repository

sites:
  - name: CoD2.ru
    url: https://cod2.ru
  #- name: Scripts
  #  url: https://script.cod2.ru
  #- name: Files
  #  url: https://files.cod2.ru
  #- name: Files Deathrun
  #  url: https://files.cod2.ru/servers/dr/blank.jpg
  #- name: Models
  #  url: https://models.cod2.ru
  # TODO udp-check
  #- name: CoD2.ru Master server
  #  check: "tcp-ping"
  #  url: master.cod2.ru
  #  port: 20710
  #- name: Global Master server
  #  check: "tcp-ping"
  #  url: cod2master.activision.com
  #  port: 20710

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cod2.ru
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CoD2.ru Upptime
  introTitle: "**CoD2.ru** status page with all the projects inside."
  introMessage: This status page uses **real-time** data from the [GitHub repository](https://github.com/lonsofore/cod2-ru-upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: http://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

